### PR TITLE
Skip python 3.10

### PR DESCRIPTION
**Pull request by giswqs**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by giswqs** [comment]
@dhirschfeld  @h-vetinari How to skip the Python 3.10 build? I added the `ray` dependency to `autogluon.core` as suggested by @Innixma at https://github.com/autogluon/autogluon/issues/612#issuecomment-1407229851. Since `ray` does not support osx, I had to remove `noarch` from the recipe. I then added the following to skip Python 3.10. Although the recipe passes all checks, the package is actually not being built and not released to conda-forge. If I don't add the follow line, the recipe fails to build because its dependency `autogluon.common` requires Python <3.10. 

```text
skip: True # [py>=310]
```

> conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("python[version='>=3.7,<3.10']"), MatchSpec("autogluon.common==0.6.2=pyhd8ed1ab_0")}

I did something similar for the `autogluon.vision` [recipe](https://github.com/conda-forge/autogluon.vision-feedstock/blob/main/recipe/meta.yaml), and it was able to build the package for Python 3.8 and 3.9.  I am not sure why `autogluon.core` did not work the same way.

**Comment by h-vetinari** [comment]
You need to rerender the recipe after changes like removing `noarch: python`, because the respective CI jobs need to be generated.

@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
note that, due to the presence of https://github.com/conda-forge/autogluon.core-feedstock/pull/6/commits/0b64c9163ce86d282c844349ebe293179ea93663, this is not correct yet (i.e. there are also builds for 3.10) - my intention here was to show the principle.

I'd suggest you `git reset --hard b0221723`, force-push this branch, and _then_ rerender

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
> note that, due to the presence of [0b64c91](https://github.com/conda-forge/autogluon.core-feedstock/commit/0b64c9163ce86d282c844349ebe293179ea93663), this is not correct yet (i.e. there are also builds for 3.10) - my intention here was to show the principle.
> 
> I'd suggest you `git reset --hard b0221723`, force-push this branch, and _then_ rerender

@h-vetinari You are life saver. Thank you very much.

**Pull request merged**
